### PR TITLE
CMD check cleanup

### PR DESCRIPTION
**Pull request by almartin82**
resolves an error and a warning from CMD check

If you want to submit this to CRAN, you're not that far away!
1.  move the `PARCC` files to a package data object
2.  .rbuildignore the image file you're using in the README
3.  resolve the 'no visible binding' stuff using one of the [strategies](https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when)

### CODE REVIEW

**Comment by almartin82** [comment]
ahh @benjaminrobinson I see what you are doing with the [NAMESPACE](https://github.com/benjaminrobinson/LearnDC/commit/202329fdc4f6829c245471c6640560b61a719f39)

this is one that I find baffling, too.
hadley [says](http://r-pkgs.had.co.nz/description.html):

> Depends: Prior to the rollout of namespaces in R 2.14.0, Depends was the only way to “depend” on another package. Now, despite the name, you should almost always use Imports, not Depends. You’ll learn why, and when you should still use Depends, in namespaces.

in practice, I end up using Depends a lot - eg, [here](https://github.com/almartin82/mapvizieR/blob/master/DESCRIPTION#L12)
basically I think if you use Imports you end up having to `::` qualify every call, or CMD check will break. 
... which I guess is good practice, but you almost never see `::` in in-the-wild R code.

that `NAMESPACE` file is auto-generated by roxygen.  I'll switch from Depends to Imports and it will effectively do the same thing as you did in your commit above.

@chrishaid do you have any thoughts on Imports vs Depends quandry?

**Comment by benjaminrobinson** [comment]
Do we need to do the same thing with jsonlite::fromJSON()?

**Comment by almartin82** [comment]
@benjaminrobinson looks like there's now a mild conflict with my branch with the DESCRIPTION file - rather than having to do a local merge, do you think you could just change it to
```
Depends:
    bitops,
    jsonlite,
    RCurl,
    R (>= 3.0.0)
```
(full file here [here](https://github.com/almartin82/LearnDC/blob/28030d102e26dc537a1ec5b6eb83c9ca686b73f4/DESCRIPTION))

on master?

**Comment by chrishaid** [comment]
I agree with Hadley, mostly.  You do see it in the wild in many packages and certainly keeps the namespace clean.  That said, if there is a single function I sue over and over,l form another package, I'll just import that function (like the magrittr pipe).  If I'm using a package and most of its functions AND I know the user will also be using package (likely having installed it before mine) the I'll put that in depends (like ggplot in the mapvizieR package).

## c

Christopher J. Haid
Director of Research & Analysis
KIPP Chicago Schools

**Comment by almartin82** [comment]
@chrishaid agreed that if the package is a common one (ggplot, dplyr etc) you're not really doing any great service by 'keeping the namespace clean'.  although I guess if you are a committed plyr person, not importing dplyr might be advantageous... although that's more of a downstream consequence of hadley's 'damn the torpedoes, I'm writing another function named filter' decision than anything else.

**Comment by benjaminrobinson** [comment]
Thanks for the input guys!  I do eventually want to push this to CRAN but I want to take a deep breath first before I do it.  I really really really appreciate all your help!

**Comment by chrishaid** [comment]
I tend to err on helping the user. dplyr, for better or worse, has functions (esp the "verbs") that share names with base functions or functions found in commonly used packages for statistical analysis (filter(), select(), order_by(), arrange() all come to mind).  So if you can avoid some pain for the user by using :: you really should.  

That said, if your package extends the functionality of another package (like ggplot does grid) the go ahead and depend that mitherfucker.

## c

Christopher J. Haid
Director of Research & Analysis
KIPP Chicago Schools

**Pull request merged**
